// src/App.vue
<template>
  <div id="app">
    <Navbar></Navbar>
    <main>
      <router-view/>
    </main>
  </div>
</template>

<script>
import Navbar from '@/components/Navbar.vue';

export default {
  name: 'app',
  components: {
    Navbar,
  },
};
</script>

<style lang="scss">
  @import '@/assets/css/application.scss';
</style>

// src/pages/_app.tsx
import React, { ReactElement } from 'react';
import "../assets/css/index.css";
import type { AppProps } from 'next/app';
import Navbar from 'components/Navbar';

const App = ({ Component, pageProps }: AppProps): ReactElement => (
  <>
    <Navbar />
    <Component {...pageProps} />
  </>
);

export default App;
